Ini, TOML
[phases.setup]
apt-packages = [
  # Required for PyAudio
  "portaudio19-dev",
  "libasound-dev",

  # General compilation tools
  "build-essential"

  # Since you have psycopg2, you may also need these:
  "libpq-dev" 
]
